// File: LineBrk.h
//
// For use with LineBreak Sample Implementation
// For additional disclaimers and description see associated LINEBREAK.CPP file
//
/*
	 Credits:
	 -------
	 Written by: Asmus Freytag
	 

	 Disclaimer and legal rights:
	 ---------------------------
	 Copyright (C) 1999-2008, ASMUS, Inc. All Rights Reserved. 
	 Distributed under the Terms of Use in http://www.unicode.org/copyright.html.

	 THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
	 OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
	 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. 
	 IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE 
	 BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, 
	 OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, 
	 WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, 
	 ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE SOFTWARE.

	 The files linebrk.vcproj, linebrk.rc, and resource.h are distributed together with this file and 
	 are included in the above.

	 --------------------------------------------------------------------------

	 Last updated: 03/04/08 - asmusf - finalized
*/

#ifndef _LINEBRRK_H_
#define _LINEBRK_H_

// --- CONDITIONAL COMPILATION FOR DEMO --------------

#if WINDOWS_UI
	// disable some warnings generated by windows.h
	#pragma warning (disable : 4514 4201)
	// Sample dialogs work better if compiled for Unicode
	#ifndef _UNICODE
	#define _UNICODE
	#endif
	#ifndef UNICODE
	#define UNICODE
	#endif
#endif

#if WINDOWS_UI > 1		// private build, files are not part of distribution
#include "main.h"		// private header, includes Windows,h
#include "window.h"   	// private header, center
#include "cmapfile.h"	// private header, table_verify
#ifdef DEBUG_ENABLED
	#define DEBUGGING 1	// conditionally enable debug support 
#endif					// for private build
#elif WINDOWS_UI > 0
#pragma message ("headers for standalone windows version")
#define ASSERT(exp) (void)( (exp) || (MessageBoxA(NULL, "Warning:  Assert Failed: " #exp, __FILE__, MB_OK), 0) ) 
#define ASSERTSZ(exp, sz) (void)( (exp) || (MessageBoxA(NULL, "Warning: " #sz "\n" #exp, __FILE__, MB_OK), 0) ) 

#include <windows.h> 	// standard include file for windows
#include <windowsx.h>  	// extended include file for windows
#include "resource.h"	// resources for standalone LineBreak dialog
#include "stdio.h"		// for table_verify
#else
// commandline version, define printf based ASSERT
#include <stdio.h>		// ASSERT and table_verify
#define ASSERT(x)		if (!(x)) \
						fprintf(stdout, "assert failed: %s\n", #x); else ;
#define ASSERTSZ(x,y)	if (!(x)) \
						fprintf(stdout, "assert failed: %s\n%s\n", #x, #y); else ;
#endif

// duplicate some windows.h defines for commandline
#ifndef TEXT
#define TCHAR  char
#define LPTSTR char *
#endif

//--- DECLARATIONS FOR DEMO UI ------
#if WINDOWS_UI
#if WINDOWS_UI > 1
BOOL CALLBACK LineBrkDlgProc(HWND hwndDlg, UINT message, WPARAM wParam, LPARAM lParam);
#else
LRESULT CALLBACK LineBrkWndProc(HWND hwndDlg, UINT message, WPARAM wParam, LPARAM lParam);
#endif
#endif

#endif // ifndef _LINEBRK_H_
